name: Deploy Infrastructure with Key Vault Integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Key Vault and Infrastructure
      run: |
        az deployment group create \
          --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV1 \
          --template-file keyVault.bicep \
        && az deployment group create \
          --resource-group aBCSAI2024-DEVOPS-STUDENTS-A-DEV \
          --template-file main.bicep
